finance/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls, name='admin'),
    path('', include('directory.urls')),
    path('', include('payments.urls')),
    path('', include('planning.urls')),
    path('', include('registers.urls')),
    path('', include('users.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]

users/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('account/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('account/register/', RegisterUserView.as_view(), name='register'),
    path('account/login/', UserLoginView.as_view(), name='login'),
    path('account/logout/', UserLogoutView.as_view(), name='logout'),
    path('account/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),
    path('account/profile/', ChangeUserInfoView.as_view(), name='personal_account'),
    path('account/password/change/', UserPasswordChangeView.as_view(), name='password_change'),
]

payments/models.py
from django.db import models

from directory.models import Organization, PaymentAccount, Currencies, Project, Counterparties, Items

from planning.models import PaymentDocumentPlan


class PaymentDocuments(models.Model):
    FlowDirection = (
        ('Receipts', 'Receipts'),
        ('Payments', 'Payments'),
    )

    flow = models.CharField(max_length=10, choices=FlowDirection, blank=True)
    organization = models.ForeignKey(Organization, on_delete=models.PROTECT, blank=False)
    date = models.DateField(blank=False)
    inflow_amount = models.DecimalField(max_digits=15, decimal_places=2, default=0, blank=False)
    outflow_amount = models.DecimalField(max_digits=15, decimal_places=2, default=0, blank=False)
    account = models.ForeignKey(PaymentAccount, on_delete=models.PROTECT, blank=False)
    currency = models.ForeignKey(Currencies, on_delete=models.PROTECT, blank=True, null=True)
    project = models.ForeignKey(Project, on_delete=models.PROTECT, blank=True, null=True)
    counterparty = models.ForeignKey(Counterparties, on_delete=models.PROTECT, blank=False)
    by_plan = models.ForeignKey(PaymentDocumentPlan, on_delete=models.PROTECT, blank=True, null=True)
    item = models.ForeignKey(Items, on_delete=models.PROTECT, blank=False)
    comments = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        if self.flow == 'Receipts':
            amount = self.inflow_amount
        else:
            amount = self.outflow_amount
        return f'{self.date}, {self.counterparty}, {self.item}, {amount}, {self.currency}, {self.flow}'


    class Meta:
        ordering = ['flow', 'organization', 'date', 'item']
        verbose_name = 'Payment document'
        verbose_name_plural = 'Payment documents'


    @classmethod
    def from_plan(cls, plan_id):
        obj = PaymentDocumentPlan.objects.get(pk=plan_id)
        return cls(
            organization=obj.organization,
            date=obj.date,
            outflow_amount=obj.outflow_amount,
            inflow_amount=obj.inflow_amount,
            currency=obj.currency,
            project=obj.project,
            counterparty=obj.counterparty,
            by_plan=obj,
            item=obj.item,
            flow=obj.flow,
            comments=obj.comments
        )



class ChangePayAccount(models.Model):
    organization = models.ForeignKey(Organization, on_delete=models.PROTECT, blank=False)
    pay_account_from = models.ForeignKey(PaymentAccount, related_name='account1', on_delete=models.PROTECT, blank=False)
    pay_account_to = models.ForeignKey(PaymentAccount, related_name='account2', on_delete=models.PROTECT, blank=False)
    date = models.DateField(blank=False)
    amount = models.DecimalField(max_digits=15, decimal_places=2, blank=False)
    currency = models.ForeignKey(Currencies, on_delete=models.PROTECT, blank=True)

    def __str__(self):
        return f'{self.date}, {self.pay_account_from}, {self.pay_account_to}, {self.amount}, {self.currency}'

    class Meta:
        ordering = ['date', 'pay_account_from', 'pay_account_to']
        verbose_name = 'Change payment account'
        verbose_name_plural = 'Changes payment account'


    # @classmethod
    # def from_plan(cls, plan_id):
    #     obj = PaymentDocuments.objects.get(pk=plan_id)
    #     return cls(
    #         organization=obj.organization,
    #         date=obj.date,
    #         outflow_amount=obj.outflow_amount,
    #         inflow_amount=obj.inflow_amount,
    #         currency=obj.currency,
    #         counterparty=obj.counterparty,
    #         item=obj.item,
    #         flow=obj.flow,
    #         comments=obj.comments
    #     )


    def get_absolute_url(self):
        return '/change_payaccounts'

receipts/templates/receipts/change_payaccounts.html
{% extends 'registers/base.html' %}
{% block title %}Change payment account{% endblock %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block content %}

<div class="container-fluid px-10">
    <div class="row">
        <div class="col-md-1 border p-2 shadow"></div>
        <form action="" method="GET"
              hx-get="/change_payaccount/list"
              hx-trigger="change"
              hx-target="#id_table">
        <div class="col-md-2 border p-2 shadow">
                <h3>Change payment account</h3>
                {% csrf_token %}
                {{ form|crispy }}
                <div hx-get="/change_payaccount/list" hx-trigger="click" hx-target="#id_table">
                    <button class="btn btn-info" type="reset" name="btn_reset" >RESET FILTERS</button>
                </div>
        </div>
            <div class="col-md-8 border p-2 shadow">
                <div class="row d-grid gap-2 d-md-flex justify-content-md-end">
                    <div class="col-md-10"></div>
                    <div class="col-md-1">
                        <a href="{% url 'change_payaccount_add' %}" class="btn btn-info" name="btn_add">ADD NEW</a>
                    </div>
                </div>
                <br>
                <div class="table table-hover table-responsive" style="height: 550px">
                    {% include "receipts/change_payaccount_list.html" %}
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}

receipts/templates/receipts/income_item_delete.html
{% extends 'registers/base.html' %}
{% block title %}Delete item{% endblock %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
    <div class="row h-100 p-2 g-3 justify-content-center" >
        <div class="col-md-8 border p-3 shadow">
             <form method="post">
                 {% csrf_token %}
                 {% if error %}
                    {{ error }}
                    {% else %}
                 <h3>Are you sure you want to delete</h3>
                 <h4>income item: "{{ object }}"</h4>
                 <br>
                 <div class="row">
                    <div class="col-md-2">
                        <button class="btn btn-info" type="submit" name="btn_del">DELETE</button>
                    </div>
                    <div class="col-md-2">
                        <a href="/income_item" class='btn btn-info'>CANCEL</a>
                    </div>
                    {% endif %}
                 </div>
             </form>
        </div>
    </div>
</div>
{% endblock %}

receipts/templates/receipts/receipts_plan.html
{% extends 'registers/base.html' %}
{% block title %}Receipts plan{% endblock %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block content %}

<div class="container-fluid px-10">
    <div class="row">
        <form action="" method="GET"
            hx-get="/receipts_plan/list"
            hx-trigger="change"
            hx-target="#id_table">
        <div class="col-md-2 border p-2 shadow">
                <h2>Planned receipts</h2>
                {% csrf_token %}
                <div class="form-group">
                {{ form.ordering.label_tag }}
                {% render_field form.ordering class="select form-control" %}
                </div>
                <div class="form-group">
                {{ form.date.label_tag }}
                {% render_field form.date class="select form-control" %}
                </div>
                <div class="form-group">
                {{ form.date_end.label_tag }}
                {% render_field form.date_end class="select form-control" %}
                </div>
                <div id="div_id_organization"
                     class="form-group"
                     hx-get="/receipts_plan/projects"
                     hx-vals="js:{organization:document.getElementById('id_organization').value}"
                     hx-trigger="change"
                     hx-target="#id_project">
                {% render_field form.organization class="select form-control" hx-get="/receipts_plan/project" hx-trigger="change" hx-target="#id_account" %}
                </div>
                <div class="form-group">
                {% render_field form.project class="select form-control" %}
                </div>
                <div class="form-group">
                {% render_field form.item class="select form-control" %}
                </div>
                <div class="form-group">
                {% render_field form.counterparty class="select form-control" %}
                </div>
                <div class="row text-left">
                    <div class="col-md-8 form-group">{% render_field form.currency class="select form-control" %}</div>
                    <div class="col-md-4 form-group">{{ form.is_cash|as_crispy_field }}</div>
                </div>
                <div hx-get="/receipts_plan/list" hx-trigger="click" hx-target="#id_table">
                    <button class="btn btn-warning" type="reset" name="btn_reset" >RESET FILTERS</button>
                </div>
        </div>
        <div class="col-md-10 border p-2 shadow">
            <div class="row d-grid gap-2 d-md-flex justify-content-md-end">
                <div class="col-md-7"></div>
                <div class="col-md-5">
                    <a href="{% url 'receipts_plan_add' %}" class="btn btn-warning" name="btn_add">ADD NEW PLAN</a>
                    <a href="{% url 'receipts_plan_upload_file' %}" class="btn btn-warning" name="btn_add">IMPORT FROM FILE</a>
                    <button  class="btn btn-warning" name="btn_to_file">SAVE TO FILE</button>
                </div>
            </div>
            <br>
            <div class="table-responsive" style="height: 550px">
                {% include "receipts/receipts_plan_list.html" %}
            </div>
        </div>
        </form>
    </div>
</div>

{% endblock %}

receipts/templates/receipts/receipts_plan_id.html
{% extends 'registers/base.html' %}
{% block title %}Receipt plan{% endblock %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block content %}

<div class="container">
    <form  method='POST'>
        {% csrf_token %}
        <div class="row text-center">
            <div class="col-md-4 border p-2 shadow"></div>
            <div class="col-md-4 border p-2 shadow">
                <h1>Planned receipt</h1>
                <div id="div_id_organization"
                     class="form-group"
                     hx-get="/receipts_plan/projects"
                     hx-vals="js:{organization:document.getElementById('id_organization').value}"
                     hx-trigger="change"
                     hx-target="#id_project">
                {% render_field form.organization class="select form-control" hx-get="/receipts_plan/project" hx-trigger="change" hx-target="#id_account" %}
                </div>
                <div class="row">
                    <div class="col-md-6 form-group">{{ form.date|as_crispy_field }}</div>
                    <div class="col-md-6 form-group">{{ form.amount|as_crispy_field }}</div>
                </div>
                <div class="row text-left">
                    <div class="col-md-8 form-group">{% render_field form.currency class="select form-control" %}</div>
                    <div class="col-md-4 form-group">{{ form.is_cash|as_crispy_field }}</div>
                </div>
                <div class="form-group">
                    {% render_field form.counterparty class="select form-control" %}
                </div>
                <div class="form-group">
                    {% render_field form.project class="select form-control" %}
                </div>
                <div class="form-group">
                    {% render_field form.item class="select form-control" %}
                </div>
                <div  class="form-group">{% render_field form.comments class="select form-control" %}</div>
                <div class="row">
                    <br>
                    <div class="col-md-12">
                        <button class="btn btn-warning" type="submit" name="btn_save">SAVE</button>
<!--                        <a href="/receipts_plan" class='btn btn-warning'>CANCEL</a>-->
                        <input action="action" onclick="window.history.go(-1); return false;"
                               class='btn btn-warning' type="submit" value="CANCEL"/>

                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

receipts/templates/receipts/receipts_plan_list.html
<table class="table table-condensed table-scroll table-striped" id="id_table" >
    <tr>
        <th align="center">organization</th>
        <th align="center">project</th>
        <th align="center">item</th>
        <th align="center">counterparty</th>
        <th align="center">date</th>
        <th align="center">amount</th>
        <th align="center">currency</th>
        <th align="center">is_cash</th>
        <th align="center">comments</th>
        <th align="center"></th>
    </tr>
    {% for i in object_list %}
    <tr>
        <td width="50">{{i.organization}}</td>
        <td width="100">{% if i.project != None %}{{ i.project }}{% endif %}</td>
        <td width="100">{{i.item}}</td>
        <td width="100">{{i.counterparty}}</td>
        <td width="50">{{i.date|date:"d.m.Y"}}</td>
        <td width="50" align="right">{{i.amount}}</td>
        <td width="50">{{i.currency}}</td>
        <td width="100">{% if i.is_cash %}<i class="bi bi-check2-square"></i>{% endif %}</td>
        <td width="100">{% if i.comments != None %}{{ i.comments }}{% endif %}</td>
        <td width="50" align="center" style='white-space: nowrap'>
            <a href="{% url 'receipts_plan_id' i.id %}" class='btn btn-warning btn-xs' data-bs-toggle="tooltip"
               data-bs-placement="top" title="edit"><i class="bi bi-pencil-square"></i></a>
            <a href="{% url 'receipts_plan_copy' i.id %}" class='btn btn-warning btn-xs' data-bs-toggle="tooltip"
               data-bs-placement="top" title="copy"><i class="bi bi-files"></i></a>
            <a href="{% url 'receipts_add_plan' i.id %}" class='btn btn-warning btn-xs' data-bs-toggle="tooltip"
               data-bs-placement="top" title="to fact"><i class="bi bi-file-earmark-arrow-up"></i></a>
            <a href="{% url 'receipts_plan_delete' i.id %}" class='btn btn-warning btn-xs' data-bs-toggle="tooltip"
               data-bs-placement="top" title="delete"><i class="bi bi-trash3"></i></a>
         </td>
    </tr>
    {% endfor %}
</table>

receipts/templates/receipts/upload_file.html
{% extends 'registers/base.html' %}
{% block title %}Receipt{% endblock %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block content %}

<div class="container">
    <form  method='POST' enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-info" type="submit" name="btn_upload">UPLOAD</button>
        <a href="/receipts" class='btn btn-info'>CANCEL</a>
    </form>
</div>
{% endblock %}